### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by syska** [twistedstream/FluentSiteMap#7]
Hi,

Pretty new to "SiteMap" but after having read multiple articles I think a custom solution based on SiteMap is the best. Since I really have xml config.

My site is in multiple languages. The setting is in a cookie and set the "CurretnUICulture" and all translatation is done custom in MVC4. I need this since its being shared so I can't force the language in the url.

I'm not using resources but my own custom translation tool.

Does FluentSiteMap support multiple sitemaps in different languages? I can't seem to find anything that says it does ...

**Comment by twistedstream** [comment]
FluentSiteMap doesn't provide any special support for multiple languages.  However, since the site map itself is a .NET class (see the [sample site map](/twistedstream/FluentSiteMap/blob/master/src/FluentSiteMap.Sample/Models/MySiteMap.cs)) and not an XML file, conceivably all you would have to do is replace all of the string literals with calls to resources.  To me that makes more sense than having multiple site map classes since you'd have to duplicate all of the fluent logic in each.

**Comment by twistedstream** [comment]
And actually, that sample site map shows how to get data from database (via a repository layer) as well as string literals.  So the fluent nature of the site map class really enables the ability to get data from anywhere.

I'm going to add something to the [README](/twistedstream/FluentSiteMap/blob/master/README.md) that describes this in a little more detail and mention your specific question about globalization support.  With that I think I'll close the issue.  Feel free to re-open it if you don't feel like this has been resolved.

**Comment by twistedstream** [comment]
Closing issue with commit b50f37fa527409f4184308bca473664c6296b504
